# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robohon_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='robohon_message.proto',
  package='robohonmessage',
  syntax='proto3',
  serialized_pb=_b('\n\x15robohon_message.proto\x12\x0erobohonmessage\"\x1c\n\x07robohon\x12\x11\n\tinfo_type\x18\x01 \x01(\t\"\x1b\n\x07\x64\x65sktop\x12\x10\n\x08sentence\x18\x01 \x01(\t2S\n\x0eRoBoHoNMessage\x12\x41\n\x0bRequestInfo\x12\x17.robohonmessage.robohon\x1a\x17.robohonmessage.desktop\"\x00\x42\x36\n\x17io.grpc.robohon_messageB\x13RoBoHoNMessageProtoP\x01\xa2\x02\x03RBHb\x06proto3')
)




_ROBOHON = _descriptor.Descriptor(
  name='robohon',
  full_name='robohonmessage.robohon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='info_type', full_name='robohonmessage.robohon.info_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=69,
)


_DESKTOP = _descriptor.Descriptor(
  name='desktop',
  full_name='robohonmessage.desktop',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sentence', full_name='robohonmessage.desktop.sentence', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=98,
)

DESCRIPTOR.message_types_by_name['robohon'] = _ROBOHON
DESCRIPTOR.message_types_by_name['desktop'] = _DESKTOP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

robohon = _reflection.GeneratedProtocolMessageType('robohon', (_message.Message,), dict(
  DESCRIPTOR = _ROBOHON,
  __module__ = 'robohon_message_pb2'
  # @@protoc_insertion_point(class_scope:robohonmessage.robohon)
  ))
_sym_db.RegisterMessage(robohon)

desktop = _reflection.GeneratedProtocolMessageType('desktop', (_message.Message,), dict(
  DESCRIPTOR = _DESKTOP,
  __module__ = 'robohon_message_pb2'
  # @@protoc_insertion_point(class_scope:robohonmessage.desktop)
  ))
_sym_db.RegisterMessage(desktop)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\027io.grpc.robohon_messageB\023RoBoHoNMessageProtoP\001\242\002\003RBH'))

_ROBOHONMESSAGE = _descriptor.ServiceDescriptor(
  name='RoBoHoNMessage',
  full_name='robohonmessage.RoBoHoNMessage',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=100,
  serialized_end=183,
  methods=[
  _descriptor.MethodDescriptor(
    name='RequestInfo',
    full_name='robohonmessage.RoBoHoNMessage.RequestInfo',
    index=0,
    containing_service=None,
    input_type=_ROBOHON,
    output_type=_DESKTOP,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ROBOHONMESSAGE)

DESCRIPTOR.services_by_name['RoBoHoNMessage'] = _ROBOHONMESSAGE

# @@protoc_insertion_point(module_scope)
